sudo: required
language: node_js
node_js:
  - "stable"

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
  - ./compileAndPackage.sh
script:
  - make test 
  - ./test
  - npm test
