# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: levy-functions

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

package:
  include:
   - bin/**
   - handler.js

functions:
  fangoostcall:
    handler: handler.fangoostcall
    events:
      - http:
          path: call/price/fangoost
          method: post
          cors: true
  fangoostcalldelta:
    handler: handler.fangoostcalldelta
    events:
      - http:
          path: call/delta/fangoost
          method: post
          cors: true
  fangoostcalltheta:
    handler: handler.fangoostcalltheta
    events:
      - http:
          path: call/theta/fangoost
          method: post
          cors: true
  fangoostcallgamma:
    handler: handler.fangoostcallgamma
    events:
      - http:
          path: call/gamma/fangoost
          method: post
          cors: true
  fangoostput:
    handler: handler.fangoostput
    events:
      - http:
          path: put/price/fangoost
          method: post
          cors: true
  fangoostputdelta:
    handler: handler.fangoostputdelta
    events:
      - http:
          path: put/delta/fangoost
          method: post
          cors: true
  fangoostputtheta:
    handler: handler.fangoostputtheta
    events:
      - http:
          path: put/theta/fangoost
          method: post
          cors: true
  fangoostputgamma:
    handler: handler.fangoostputgamma
    events:
      - http:
          path: put/gamma/fangoost
          method: post
          cors: true

  carrmadanput:
    handler: handler.carrmadanput
    events:
      - http:
          path: put/price/carrmadan
          method: post
          cors: true

  carrmadancall:
    handler: handler.carrmadancall
    events:
      - http:
          path: call/price/carrmadan
          method: post
          cors: true

  fstsput:
    handler: handler.fstsput
    events:
      - http:
          path: put/price/fsts
          method: post
          cors: true
  fstscall:
    handler: handler.fstscall
    events:
      - http:
          path: call/price/fsts
          method: post
          cors: true
  fstsputdelta:
    handler: handler.fstsputdelta
    events:
      - http:
          path: put/delta/fsts
          method: post
          cors: true
  fstscalldelta:
    handler: handler.fstscalldelta
    events:
      - http:
          path: call/delta/fsts
          method: post
          cors: true
  fstsputtheta:
    handler: handler.fstsputtheta
    events:
      - http:
          path: put/theta/fsts
          method: post
          cors: true
  fstscalltheta:
    handler: handler.fstscalltheta
    events:
      - http:
          path: call/theta/fsts
          method: post
          cors: true
  fstsputgamma:
    handler: handler.fstsputgamma
    events:
      - http:
          path: put/gamma/fsts
          method: post
          cors: true
  fstscallgamma:
    handler: handler.fstscallgamma
    events:
      - http:
          path: call/gamma/fsts
          method: post
          cors: true
  VaR:
    handler: handler.VaR
    events:
      - http:
          path: density/var
          method: post
          cors: true
  density:
    handler: handler.density
    events:
      - http:
          path: density/raw
          method: post
          cors: true
  fullmodel:
    handler: handler.fullmodel
    memorySize: 3008 # optional, in MB, default is 1024
    timeout: 60 # optional, in seconds, default is 6
    events:
      - http:
          path: call/calibration/full
          method: post
          cors: true
  hestonmodel:
    handler: handler.hestonmodel
    memorySize: 3008 # optional, in MB, default is 1024
    timeout: 60 # optional, in seconds, default is 6
    events:
      - http:
          path: call/calibration/heston
          method: post
          cors: true
  bsmodel:
    handler: handler.bsmodel
    memorySize: 3008 # optional, in MB, default is 1024
    timeout: 60 # optional, in seconds, default is 6
    events:
      - http:
          path: call/calibration/bs
          method: post
          cors: true
      

